// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGV6aMSv20cA9jjneXWYlODQDpo340rY',
    appId: '1:837319059454:web:a39b52c594b9f2221882af',
    messagingSenderId: '837319059454',
    projectId: 'clone-a1fc5',
    authDomain: 'clone-a1fc5.firebaseapp.com',
    storageBucket: 'clone-a1fc5.appspot.com',
    measurementId: 'G-VLS2WJJQN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp9ovMSfDiNuPmINd9VpWkxhvFS3D6WKM',
    appId: '1:837319059454:android:a8accd61457a48981882af',
    messagingSenderId: '837319059454',
    projectId: 'clone-a1fc5',
    storageBucket: 'clone-a1fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANS3fVvBxBbbkyOxoYJTAgYvzVB1kueGU',
    appId: '1:837319059454:ios:70c5e774c6a3da181882af',
    messagingSenderId: '837319059454',
    projectId: 'clone-a1fc5',
    storageBucket: 'clone-a1fc5.appspot.com',
    iosClientId: '837319059454-07vov7jlmmk7isgj7ic6iu9bfvgesl8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANS3fVvBxBbbkyOxoYJTAgYvzVB1kueGU',
    appId: '1:837319059454:ios:70c5e774c6a3da181882af',
    messagingSenderId: '837319059454',
    projectId: 'clone-a1fc5',
    storageBucket: 'clone-a1fc5.appspot.com',
    iosClientId: '837319059454-07vov7jlmmk7isgj7ic6iu9bfvgesl8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKGV6aMSv20cA9jjneXWYlODQDpo340rY',
    appId: '1:837319059454:web:e15030be22e725a51882af',
    messagingSenderId: '837319059454',
    projectId: 'clone-a1fc5',
    authDomain: 'clone-a1fc5.firebaseapp.com',
    storageBucket: 'clone-a1fc5.appspot.com',
    measurementId: 'G-ZCKHBTNHSC',
  );

}